export const ERROR = 'ERROR';
export const RECEIVED_ENTITIES = 'RECEIVED_ENTITIES';

export const SIGNIN = 'SIGNIN';
export const SIGNUP = 'SIGNUP';
export const SIGNOUT = 'SIGNOUT';

export const ADD_PROJECT = 'ADD_PROJECT';
export const INSERT_PROJECT = 'INSERT_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const FIND_ALL_PROJECT = 'FIND_ALL_PROJECT';
export const FIND_PROJECT = 'FIND_PROJECT';

export const ADD_CHECKLIST = 'ADD_CHECKLIST';
export const INSERT_CHECKLIST = 'INSERT_CHECKLIST';
export const UPDATE_CHECKLIST = 'UPDATE_CHECKLIST';
export const DELETE_CHECKLIST_SUCCESS = 'DELETE_CHECKLIST_SUCCESS';
export const CREATE_VERSION_CHECKLIST_SUCCESS = 'CREATE_VERSION_CHECKLIST_SUCCESS';
